version: '3.8'

services:
  freecad:
    build: .
    container_name: freecad-vscode
    ports:
      - "${SSH_PORT}:2222"     # SSH port for VSCode remote connection
      - 3000:3000             # FreeCAD GUI HTTP
      - 3001:3001             # FreeCAD GUI HTTPS
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./config:/config
      - ./projects:/root/projects    # Mount your code/projects here for editing
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
