version: "3.8"

services:
  freecad-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freecad-dev
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ${HOME}/my_code/freecad_source:/mnt/source
      - ${HOME}/my_code/freecad_build:/mnt/build
      - ${HOME}:/mnt/files
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    network_mode: "host"  # allows GUI forwarding without extra config
    stdin_open: true
    tty: true
